// Babcock University undergraduate programmes (used in the voter request form).
export const DEPARTMENTS = [
  "B.Sc Software Engineering",
  "B.A History And International Studies",
  "B.A. English Studies",
  "B.A French And Foreign Studies",
  "B.A Christian Religious Studies",
  "B.A Music",
  "B.A English Language Education",
  "B.Sc Business Education",
  "B.Ed Educational Planning & Administration",
  "B.Sc Guidance and Counseling",
  "B.Sc Business Administration",
  "B.Sc Accounting",
  "B.Sc Agricultural Economics and Extension",
  "B.Sc Animal Science",
  "B.Sc Biochemistry",
  "B.Sc Computer Science",
  "B.Sc Economics",
  "B.Sc Finance",
  "B.Sc Information Technology",
  "B.Sc Mass Communication",
  "B.Sc Microbiology",
  "B.Sc Physiology",
  "B.Sc Political Science",
  "B.Sc Public Health",
  "BML.S Medical Laboratory Science",
  "BIRM Information Resources Management",
  "Bachelors in Social Work and Human Services",
  "Medicine (MBBS)",
  "B.NSc Nursing",
];
